name: 'dbt_interview'
version: '1.0.0'
config-version: 2

profile: 'default'

flags:
  send_anonymous_usage_stats: false

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dbt_interview:
    +database: dbt
    +persist_docs:
      relation: true
      columns: true
    staging:
      +schema: staging
      +materialized: view
      +tags: ['staging', 'raw']
    intermediate:
      +materialized: table
      +schema: intermediate
      +tags: ['intermediate', 'daily']
    marts:
      +schema: marts
      +materialized: table
      +tags: ['marts', 'daily']

seeds:
  dbt_interview:
    +database: dbt
    +schema: seeds

snapshots:
  dbt_interview:
    +database: dbt
    +schema: snapshots

vars:
  "dbt_date:time_zone": "Europe/Berlin"
